### ISSUE TITLE
Add QC to remove observations on/near land

### ISSUE THREAD

**Issue by travissluka** [UMD-AOSC/OISSTv3#54]
We need QC filters to properly remove SST observations that are on, or too close, to land (The current method of relying on bad large values will stop working once I add masking to the interpolation)

1. Add `sea_area_fraction` to `GetValues`. Similar to how `sea_surface_temperature` works there, except pull the data from the land mask that was just added to `Geometry`. This does **not** need to be added to the `LinearGetValues`
2. add a QC filter in the yaml for the var:
```yaml
  filter: Domain Check
  where:
  - variable: {name: sea_area_fraction@GeoVaLs}
    minvalue: 1.0
```

You should be able to disable the current QC bound check filter, use this land mask check instead, and have to Var produce valid answers still
